package vodacomgo

var LoginRx = `<?xml version='1.0' encoding='UTF-8'?>
<S:Envelope
    xmlns:S="http://schemas.xmlsoap.org/soap/envelope/"
    xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/">
    <S:Header>
        <ns3:eventid
            xmlns:ns2="http://www.4cgroup.co.za/genericsoap"
            xmlns:ns3="http://www.4cgroup.co.za/soapauth">2500
        </ns3:eventid>
    </S:Header>
    <S:Body>
        <ns2:getGenericResultResponse
            xmlns:ns2="http://www.4cgroup.co.za/genericsoap"
            xmlns:ns3="http://www.4cgroup.co.za/soapauth">
            <SOAPAPIResult>
                <eventInfo>
                    <code>3</code>
                    <description>Processed</description>
                    <detail>Processed</detail>
                    <transactionID>0c49ec4bbebe44b082aa24e5f548b514</transactionID>
                </eventInfo>
                <request>
                    <dataItem>
                        <name>Username</name>
                        <type>String</type>
                        <value>thirdpartyc2bw</value>
                    </dataItem>
                    <dataItem>
                        <name>Password</name>
                        <type>String</type>
                        <value>thirdpartyc2bw</value>
                    </dataItem>
                </request>
                <response>
                    <dataItem>
                        <name>SessionID</name>
                        <type>String</type>
                        <value>dbcb63a40afd4191a990d66ed9cb62f7</value>
                    </dataItem>
                </response>
            </SOAPAPIResult>
        </ns2:getGenericResultResponse>
    </S:Body>
</S:Envelope>
`

var C2BRx = `<?xml version='1.0' encoding='UTF-8'?>
<S:Envelope
    xmlns:S="http://schemas.xmlsoap.org/soap/envelope/"
    xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/">
    <S:Header>
        <ns3:eventid
            xmlns:ns2="http://www.4cgroup.co.za/genericsoap"
            xmlns:ns3="http://www.4cgroup.co.za/soapauth">80049
        </ns3:eventid>
    </S:Header>
    <S:Body>
        <ns2:getGenericResultResponse
            xmlns:ns2="http://www.4cgroup.co.za/genericsoap"
            xmlns:ns3="http://www.4cgroup.co.za/soapauth">
            <SOAPAPIResult>
                <eventInfo>
                    <code>3</code>
                    <description>Processed</description>
                    <detail>Processed</detail>
                    <transactionID>80db41ffab3c4b88ab7f937f9fd7ccc9</transactionID>
                </eventInfo>
                <request>
                    <dataItem>
                        <name>CustomerMSISDN</name>
                        <type>String</type>
                        <value>243811835361</value>
                    </dataItem>
                    <dataItem>
                        <name>ServiceProviderCode</name>
                        <type>String</type>
                        <value>8337</value>
                    </dataItem>
                    <dataItem>
                        <name>Currency</name>
                        <type>String</type>
                        <value>CDF</value>
                    </dataItem>
                    <dataItem>
                        <name>Amount</name>
                        <type>String</type>
                        <value>10</value>
                    </dataItem>
                    <dataItem>
                        <name>Date</name>
                        <type>String</type>
                        <value>20170901155250</value>
                    </dataItem>
                    <dataItem>
                        <name>ThirdPartyReference</name>
                        <type>String</type>
                        <value>Test100</value>
                    </dataItem>
                    <dataItem>
                        <name>CommandId</name>
                        <type>String</type>
                        <value>InitTrans_oneForallC2B</value>
                    </dataItem>
                    <dataItem>
                        <name>Language</name>
                        <type>String</type>
                        <value>EN</value>
                    </dataItem>
                    <dataItem>
                        <name>CallBackChannel</name>
                        <type>String</type>
                        <value>4</value>
                    </dataItem>
                    <dataItem>
                        <name>CallBackDestination</name>
                        <type>String</type>
                        <value>Christian.Belewete@vodacom.cd</value>
                    </dataItem>
                    <dataItem>
                        <name>Surname</name>
                        <type>String</type>
                        <value>Surname</value>
                    </dataItem>
                    <dataItem>
                        <name>Initials</name>
                        <type>String</type>
                        <value>Initials</value>
                    </dataItem>
                </request>
                <response>
                    <dataItem>
                        <name>InsightReference</name>
                        <type>String</type>
                        <value>7272C194D0B50616E054002128FBA42E</value>
                    </dataItem>
                    <dataItem>
                        <name>ResponseCode</name>
                        <type>String</type>
                        <value>0</value>
                    </dataItem>
                    <dataItem>
                        <name>CustomerMSISDN</name>
                        <type>String</type>
                        <value>243811835361</value>
                    </dataItem>
                </response>
            </SOAPAPIResult>
        </ns2:getGenericResultResponse>
    </S:Body>
</S:Envelope>
`

var B2CRx = `<?xml version='1.0' encoding='UTF-8'?>
<S:Envelope xmlns:S="http://schemas.xmlsoap.org/soap/envelope/" xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/">
  <S:Header>
    <ns3:eventid xmlns:ns2="http://www.4cgroup.co.za/genericsoap" xmlns:ns3="http://www.4cgroup.co.za/soapauth">80049 </ns3:eventid>
  </S:Header>
  <S:Body>
    <ns2:getGenericResultResponse xmlns:ns2="http://www.4cgroup.co.za/genericsoap" xmlns:ns3="http://www.4cgroup.co.za/soapauth">
      <SOAPAPIResult>
        <eventInfo>
          <code>3</code>
          <description>Processed</description>
          <detail>Processed</detail>
          <transactionID>80db41ffab3c4b88ab7f937f9fd7ccc9</transactionID>
        </eventInfo>
        <request>
          <dataItem>
            <name>ServiceProviderName</name>
            <type>String</type>
            <value>ONE4ALL</value>
          </dataItem>
          <dataItem>
            <name>CustomerMSISDN</name>
            <type>String</type>
            <value>243811835361</value>
          </dataItem>
          <dataItem>
            <name>Currency</name>
            <type>String</type>
            <value>CDF</value>
          </dataItem>
          <dataItem>
            <name>Amount</name>
            <type>String</type>
            <value>5000</value>
          </dataItem>
          <dataItem>
            <name>TransactionDateTime</name>
            <type>Date</type>
            <value>20190901155250</value>
          </dataItem>
          <dataItem>
            <name>Shortcode</name>
            <type>String</type>
            <value>15058</value>
          </dataItem>
          <dataItem>
            <name>Language</name>
            <type>String</type>
            <value>EN</value>
          </dataItem>
          <dataItem>
            <name>ThirdPartyReference</name>
            <type>String</type>
            <value>Test100</value>
          </dataItem>
          <dataItem>
            <name>CallBackChannel</name>
            <type>String</type>
            <value>4</value>
          </dataItem>
          <dataItem>
            <name>CallBackDestination</name>
            <type>String</type>
            <value>Christian.Belewete@vodacom.cd</value>
          </dataItem>
          <dataItem>
            <name>CommandID</name>
            <type>String</type>
            <value>InitTrans_one4allb2c</value>
          </dataItem>
        </request>
        <response>
          <dataItem>
            <name>InsightReference</name>
            <type>String</type>
            <value>7272C194D0B50616E054002128FBA42E</value>
          </dataItem>
          <dataItem>
            <name>ResponseCode</name>
            <type>String</type>
            <value>0</value>
          </dataItem>
          <dataItem>
            <name>CustomerMSISDN</name>
            <type>String</type>
            <value>243811835361</value>
          </dataItem>
        </response>
      </SOAPAPIResult>
    </ns2:getGenericResultResponse>
  </S:Body>
</S:Envelope>
`

var C2BCRx = `<soapenv:Envelope xmlns:soapenv='http://schemas.xmlsoap.org/soap/envelope/' xmlns:soap='http://www.4cgroup.co.za/soapauth' xmlns:gen='http://www.4cgroup.co.za/genericsoap'>
  <soapenv:Body>
    <gen:getGenericResult>
      <Request>
        <dataItem>
          <name>ResultType</name>
          <value>-1</value>
          <type>String</type>
        </dataItem>
        <dataItem>
          <name>ResultCode</name>
          <value>-3</value>
          <type>String</type>
        </dataItem>
        <dataItem>
          <name>ResultDesc</name>
          <value>Failed response initiating payment .</value>
          <type>String</type>
        </dataItem>
        <dataItem>
          <name>OriginatorConversationID</name>
          <value>-1</value><type>String</type>
        </dataItem>
        <dataItem>
          <name>ConversationID</name>
          <value>-1</value>
          <type>String</type>
        </dataItem>
        <dataItem>
          <name>ThirdPartyReference</name>
          <value>R20201127204705</value>
          <type>String</type>
        </dataItem>
        <dataItem>
          <name>Amount</name>
          <value>1000</value>
          <type>String</type>
        </dataItem>
        <dataItem>
          <name>TransactionTime</name>
          <value>-1</value>
          <type>String</type>
        </dataItem>
        <dataItem>
          <name>InsightReference</name>
          <value>B51D9D0A488C5882E0536C045A0AFD1D</value>
          <type>String</type>
        </dataItem>
        <dataItem>
          <name>TransactionID</name>
          <value>-1</value>
          <type>String</type>
        </dataItem>
      </Request>
    </gen:getGenericResult>
  </soapenv:Body>
</soapenv:Envelope>
`

var B2CCRx = `<?xml version="1.0" encoding="utf-8"?>
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:soap="http://www.4cgroup.co.za/soapauth" xmlns:gen="http://www.4cgroup.co.za/genericsoap">
  <soapenv:Header>
    <soap:EventID>1</soap:EventID>
  </soapenv:Header>
  <soapenv:Body>
    <gen:getGenericResult>
      <Request>
        <dataItem>
          <name>ResultType</name>
          <value>0</value>
          <type>String</type>
        </dataItem>
        <dataItem>
          <name>ResultCode</name>
          <value>0</value>
          <type>String</type>
        </dataItem>
        <dataItem>
          <name>ResultDesc</name>
          <value> Process service request successfully.</value>
          <type>String</type>
        </dataItem>
        <dataItem>
          <name>OriginatorConversationId</name>
          <value>fbb550d9eb924e8e99ac1aa7ff8c05d0</value>
          <type>String</type>
        </dataItem>
        <dataItem>
          <name>ConversationId</name>
          <value>0c9766a5-1c9e-4ffa-b815-3b447dde5cb1</value>
          <type>String</type>
        </dataItem>
        <dataItem>
          <name>TransactionID</name>
          <value>X-BS281</value>
          <type>String</type>
        </dataItem>
        <dataItem>
          <name>Amount</name>
          <value>200</value>
          <type>String</type>
        </dataItem>
        <dataItem>
          <name>TransactionTime</name>
          <value>20170301T22:59:01</value>
          <type>String</type>
        </dataItem>
        <dataItem>
          <name>ThirdPartyReference</name>
          <value>123456-Test</value>
          <type>String</type>
        </dataItem>
        <dataItem>
          <name>InsightReference</name>
          <value>12sdxq3634dadsas242</value>
          <type>String</type>
        </dataItem>
      </Request>
    </gen:getGenericResult>
  </soapenv:Body>
</soapenv:Envelope>
`
