package vodacomgo

var LoginT = `<?xml version="1.0" encoding="UTF-8"?>
<soapenv:Envelope
    xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"
    xmlns:soap="http://www.4cgroup.co.za/soapauth"
    xmlns:gen="http://www.4cgroup.co.za/genericsoap">
    <soapenv:Header>
        <soap:EventID>2500</soap:EventID>
    </soapenv:Header>
    <soapenv:Body>
        <gen:getGenericResult>
            <Request>
                <dataItem>
                    <name>Username</name>
                    <type>String</type>
                    <value>{{.Username}}</value>
                </dataItem>
                <dataItem>
                    <name>Password</name>
                    <type>String</type>
                    <value>{{.Password}}</value>
                </dataItem>
            </Request>
        </gen:getGenericResult>
    </soapenv:Body>
</soapenv:Envelope>
`

var C2BT = `<?xml version="1.0" encoding="UTF-8"?>
<soapenv:Envelope
    xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"
    xmlns:soap="http://www.4cgroup.co.za/soapauth"
    xmlns:gen="http://www.4cgroup.co.za/genericsoap">
    <soapenv:Header>
        <soap:Token
            xmlns:soap="http://www.4cgroup.co.za/soapauth">{{.Token}}</soap:Token>
        <soap:EventID>80049</soap:EventID>
    </soapenv:Header>
    <soapenv:Body>
        <gen:getGenericResult>
            <Request>
                <dataItem>
                    <name>CustomerMSISDN</name>
                    <type>String</type>
                    <value>{{.CustomerMSISDN}}</value>
                </dataItem>
                <dataItem>
                    <name>ServiceProviderCode</name>
                    <type>String</type>
                    <value>{{.ServiceProviderCode}}</value>
                </dataItem>
                <dataItem>
                    <name>Currency</name>
                    <type>String</type>
                    <value>{{.Currency}}</value>
                </dataItem>
                <dataItem>
                    <name>Amount</name>
                    <type>String</type>
                    <value>{{.Amount}}</value>
                </dataItem>
                <dataItem>
                    <name>Date</name>
                    <type>String</type>
                    <value>{{.Date}}</value>
                </dataItem>
                <dataItem>
                    <name>ThirdPartyReference</name>
                    <type>String</type>
                    <value>{{.ThirdPartyReference}}</value>
                </dataItem>
                <dataItem>
                    <name>CommandId</name>
                    <type>String</type>
                    <value>{{.CommandID}}</value>
                </dataItem>
                <dataItem>
                    <name>Language</name>
                    <type>String</type>
                    <value>{{.Language}}</value>
                </dataItem>
                <dataItem>
                    <name>CallBackChannel</name>
                    <type>String</type>
                    <value>{{.CallBackChannel}}</value>
                </dataItem>
                <dataItem>
                    <name>CallBackDestination</name>
                    <type>String</type>
                    <value>{{.CallBackDestination}}</value>
                </dataItem>
                <dataItem>
                    <name>Surname</name>
                    <type>String</type>
                    <value>{{.Surname}}</value>
                </dataItem>
                <dataItem>
                    <name>Initials</name>
                    <type>String</type>
                    <value>{{.Initials}}</value>
                </dataItem>
            </Request>
        </gen:getGenericResult>
    </soapenv:Body>
</soapenv:Envelope>
`
var B2CT = `<?xml version="1.0" encoding="UTF-8"?>
<soapenv:Envelope
    xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">
    <soapenv:Header>
        <soap:EventID
            xmlns:soap="http://www.4cgroup.co.za/soapauth">12001</soap:EventID>
        <soap:Token
            xmlns:soap="http://www.4cgroup.co.za/soapauth">{{.Token}}</soap:Token>
    </soapenv:Header>
    <soapenv:Body>
        <gen:getGenericResult
            xmlns:gen="http://www.4cgroup.co.za/genericsoap">
            <Request>
                <dataItem>
                    <name>ServiceProviderName</name>
                    <type>String</type>
                    <value>{{.ServiceProviderName}}</value>
                </dataItem>
                <dataItem>
                    <name>CustomerMSISDN</name>
                    <type>String</type>
                    <value>{{.CustomerMSISDN}}</value>
                </dataItem>
                <dataItem>
                    <name>Currency</name>
                    <type>String</type>
                    <value>{{.Currency}}</value>
                </dataItem>
                <dataItem>
                    <name>Amount</name>
                    <type>String</type>
                    <value>{{.Amount}}</value>
                </dataItem>
                <dataItem>
                    <name>TransactionDateTime</name>
                    <type>Date</type>
                    <value>{{.TransactionDateTime}}</value>
                </dataItem>
                <dataItem>
                    <name>Shortcode</name>
                    <type>String</type>
                    <value>{{.Shortcode}}</value>
                </dataItem>
                <dataItem>
                    <name>Language</name>
                    <type>String</type>
                    <value>{{.Language}}</value>
                </dataItem>
                <dataItem>
                    <name>ThirdPartyReference</name>
                    <type>String</type>
                    <value>{{.ThirdPartyReference}}</value>
                </dataItem>
                <dataItem>
                    <name>CallBackChannel</name>
                    <type>String</type>
                    <value>{{.CallBackChannel}}</value>
                </dataItem>
                <dataItem>
                    <name>CallBackDestination</name>
                    <type>String</type>
                    <value>{{.CallBackDestination}}</value>
                </dataItem>
                <dataItem>
                    <name>CommandID</name>
                    <type>String</type>
                    <value>{{.CommandID}}</value>
                </dataItem>
            </Request>
        </gen:getGenericResult>
    </soapenv:Body>
</soapenv:Envelope>
`

var AckB2CT = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<response>
  <dataItem>
    <name>ResponseCode</name>
    <type>String</type>
    <value>200</value>
  </dataItem>
  <dataItem>
    <name>RESULT_CODE</name>
    <type>String</type>
    <value>Received</value>
  </dataItem>
</response>
`
var AckC2BT = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<response>
  <dataItem>
    <name>ResponseCode</name>
    <type>String</type>
    <value>200</value>
  </dataItem>
</response>
`
